server:
  port: 8001
ProviderVersion: UserProvider0.0.4
spring:
  datasource:
    url: jdbc:mysql://db1:3306/springboot-005?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka,http://eureka2:10087/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
