server:
  port: 9004
spring:
  thymeleaf:
    cache: false
  application:
    name: UserWeb04

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka,http://eureka2:10087/eureka
logging:
  level:
    com:
      offcn: debug
feign:
  hystrix:
    enabled: true
#设定Hystrix熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
